= Gradle Job DSL support plugin

This plugin provides some support tasks for maintaining a
https://github.com/jenkinsci/job-dsl-plugin[Jenkins Job DSL Script]
repository/project.

== Features

* Local tests of DSL scripts
** Ensures DSL scripts execute without error
** Supports external Job DSL extensions from Jenkins plugins
* Local generation of Jenkins config XML files
* Support for external library dependencies for use in your DSL scripts

== Configuration

build.gradle:

[source,gradle]
----
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.aoe.gradle:jenkins-job-dsl-gradle-plugin:1.3.0'
    }
}

apply plugin: 'com.aoe.jenkins-job-dsl'

dependencies {
    // Example for using additional Jenkins plugins that provide their own Job DSL support:
    jobDslExtension 'com.aoe.jenkins:scm-push-trigger:1.1.0@jar'

    // Example for using external libraries in the DSL scripts themselves:
    compile 'com.google.guava:guava:18.0'
}

jobDsl {
    // Base directory where the DSL scripts reside
    sourceDir 'src/jobs'

    // Aditional non-DSL-script resources needed from the DSL scripts
    resourceDir 'src/configs'

    // Version of Job DSL you want to use
    version = '1.40' // default

    // By default jcenter and jenkins-release are added as repositories
    // If you don't like this set it to false
    addRepositories = true // default
}

----

== Structure

Put your DSL scripts into a directory under root like e.g. `src/jobs`.

If you have additional files that are not DSL scripts (like config) put them
into their own base dir.  A good choice is `src/configs`.

Then add these base dirs to the `jobDsl` section in the `build.gradle`:
[source,gradle]
----
jobDsl {
    sourceDir 'src/jobs'
    resourceDir 'src/configs'
}
----

It is possible to have multiple sourceDirs and resourceDirs.

== Additional libraries

You can use additional libraries by simply declaring them as a dependency in the
`build.gradle`:

[source,gradle]
----
dependencies {
    compile 'com.aoe.groovy:groovy-guava:1.2.2'
}
----

There is a task `libs` that copies all `compile` dependencies into the `lib`
folder in the base dir (so put that into .gitignore). 

This should be configured as an additional classpath in the seeder job
in Jenkins (e.g. `lib/*.jar`). 

== Usage

* `gradlew build` - Compile code in `src/main/groovy`, execute tests and copy
  compile dependencies into `lib` folder (calls `libs` task)
* `gradlew testDsl` - Executes all DSL scripts to ensure no error. If everything
  is fine Gradle will say `BUILD SUCCESSFUL`. Otherwise open the test report
  from `build/reports/test/index.html`.
* `gradlew runAll` - Execute all DSL scripts or:
* `gradlew run -PjobFile=src/jobs/myjob.groovy` - Generate only a specific
  script. The results are available in `build/workspace`.

== Jenkins Seeder Job Configuration

This is the recommended configuration of the seeder job on Jenkins. Adapt where
needed. For a general introduction refer to the
https://github.com/jenkinsci/job-dsl-plugin/wiki/Tutorial---Using-the-Jenkins-Job-DSL[tutorial
at the Job DSL site]

First configure a _Invoke Gradle script_ step with the tasks `clean build`.
This will build everything, run the tests and download additional libraries (if
used) to the local `lib` directory.

Next add a step _Process Job DSLs_. Configure it for using the DSL scripts in
your repo (_Look on filesystem_). If you store them like in the above example in `src/jobs` configure
the step for using `src/jobs/\**/*.groovy`.

In the _Advanced_ section you should set up an additional classpath to include
your (optional) local support code and / or libraries:

----
build/classes/main
lib/*.jar
----

